on: pull_request

name: test_action
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.7"]
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Deploy testnet for test
        run: |
          #环境部署
          sleep 15
      - name: Test with pytest
        run: |
          bash run_case.sh batch3
